--- @module 'gears'
local gears

--- The X window id.
---## Constraints
--- - Access: read-only
--- - Default value: This is generated by X11.
--- - Negative allowed: false
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#window)
--- @alias ClientPropertyWindow integer
--- @type ClientPropertyWindow
client.window = nil

--- The client title.
---## Constraints
--- - Default value: This is provided by the application.
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#name)
--- @alias ClientPropertyName string
--- @type ClientPropertyName
client.name = nil

--- True if the client does not want to be in taskbar.
---## Constraints
--- - Default value: `false`
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#skip_taskbar)
--- @alias ClientPropertySkipTaskbar boolean
--- @type ClientPropertySkipTaskbar
client.skip_taskbar = false

--- The window type.
---## Constraints
--- - Access: read-only
--- - Default value: This is provided by the application.
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#type)
--- @alias ClientPropertyType string
--- @type ClientPropertyType
client.type = nil

--- The client class.
---## Constraints
--- - Access: read-only
--- - Default value: This is provided by the application.
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#class)
--- @alias ClientPropertyClass string
--- @type ClientPropertyClass
client.class = nil

--- The client instance.
---## Constraints
--- - Access: read-only
--- - Default value: This is provided by the application.
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#instance)
--- @alias ClientPropertyInstance string
--- @type ClientPropertyInstance
client.instance = nil

--- The client PID, if available.
---## Constraints
--- - Access: read-only
--- - Default value: This is randomly assigned by the kernel.
--- - Negative allowed: false
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#pid)
--- @alias ClientPropertyPid integer
--- @type ClientPropertyPid
client.pid = nil

--- The window role, if available.
---## Constraints
--- - Access: read-only
--- - Default value: This is provided by the application.
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#role)
--- @alias ClientPropertyRole string
--- @type ClientPropertyRole
client.role = nil

--- The machine the client is running on.
---## Constraints
--- - Access: read-only
--- - Default value: This is the hostname unless the client is from an SSH session or using the rarely used direct X11 network socket.
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#machine)
--- @alias ClientPropertyMachine string
--- @type ClientPropertyMachine
client.machine = nil

--- The client name when iconified.
---## Constraints
--- - Default value: This is provided by the application.
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#icon_name)
--- @alias ClientPropertyIconName string
--- @type ClientPropertyIconName
client.icon_name = nil

--- The client icon as a surface.
---## Constraints
--- - Default value: This is provided by the application.
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#icon)
--- @alias ClientPropertyIcon DrawableImage
--- @type ClientPropertyIcon
client.icon = nil

--- The available sizes of client icons.
---## Constraints
--- - Access: read-only
--- - Default value: This is provided by the application.
--- - Table content: A list of tables. Each table has the following rows:
---   - __[1]__: The width value.
---   - __[2]__: The height value.
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#icon_sizes)
--- @alias ClientPropertyIconSizes integer[][]
--- @type ClientPropertyIconSizes
client.icon_sizes = nil

--- Client screen.
---
---## Constraints
--- - Default value: This usually correspond to where the top-left (or other gravities) is placed. Then it is mapped to the screen `geometry`.
--- - Type description:
---   - screen: A valid screen object such as retured by `awful.screen.focused()` or mouse.screen.
---   - integer: A screen global id. Avoid using this since they are unsorted.
---   - string: The `"primary"` value is also valid.
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#screen)
--- @alias ClientPropertyScreen
--- | Screen A valid screen object such as retured by `awful.screen.focused()` or mouse.screen.
--- | integer A screen global id. Avoid using this since they are unsorted.
--- | string The `"primary"` value is also valid.
--- @type ClientPropertyScreen
client.screen = nil

--- Define if the client must be hidden (Never mapped, invisible in taskbar).
---## Constraints
--- - Default value: `false`
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#hidden)
--- @alias ClientPropertyHidden boolean
--- @type ClientPropertyHidden
client.hidden = false

--- Define if the client must be iconified (Only visible in taskbar).
---## Constraints
--- - Default value: `false`
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#minimized)
--- @alias ClientPropertyMinimized boolean
--- @type ClientPropertyMinimized
client.minimized = false

--- Honor size hints, e.g. respect size ratio.
---## Constraints
--- - Default value: `true`
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#size_hints_honor)
--- @alias ClientPropertySizeHintsHonor boolean
--- @type ClientPropertySizeHintsHonor
client.size_hints_honor = true

--- The client border width.
---## Constraints
--- - Default value: `nil`
--- - Type description:
---   - nil: Let AwesomeWM manage it based on the client state.
--- - Unit: pixel
--- - Negative allowed: false
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#border_width)
--- @alias ClientPropertyBorderWidth integer|nil
--- @type ClientPropertyBorderWidth
client.border_width = nil

--- The client border color.
---## Constraints
--- - Default value: nil
--- - Type description: nil: Let AwesomeWM manage it based on the client state.
---   - string: An hexadecimal color code, such as `"#ff0000"` for red.
---   - string: A color name, such as `"red"`.
---   - table: A [gradient table](https://awesomewm.org/apidoc/theme_related_libraries/gears.color.html).
---   - cairo.pattern: Any valid [Cairo pattern](https://cairographics.org/manual/cairo-cairo-pattern-t.html).
---   - cairo.pattern: A texture build from an image by [gears.color.create_png_pattern](https://awesomewm.org/apidoc/theme_related_libraries/gears.color.html#create_png_pattern)
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#border_color)
--- @diagnostic disable-next-line: undefined-doc-name
--- @alias ClientPropertyBorderColor string|table|cairo.pattern|nil
--- @type ClientPropertyBorderColor
client.border_color = nil

--- Set to `true` when the client ask for attention.
---## Constraints
--- - Default value: `false`
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#urgent)
--- @alias ClientPropertyUrgent boolean
--- @type ClientPropertyUrgent
client.urgent = false

--- A cairo surface for the client window content.
---## Constraints
--- - Access: read-only
--- - Default value: This is a live surface. Always use [gears.surface](https://awesomewm.org/apidoc/libraries/gears.surface.html) to take a snapshot.
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#content)
--- @alias ClientPropertyContent CAPICairoSurface
--- @type ClientPropertyContent
client.content = nil

--- The client opacity.
---## Constraints
--- - Default value: `1.0`
--- - Minimum value: 0.0 Transparent.
--- - Maximum value: 1.0 Opaque.
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#opacity)
--- @alias ClientPropertyOpacity number
--- @type ClientPropertyOpacity
client.opacity = 1.0

--- The client is on top of every other windows.
---## Constraints
--- - Default value: `false`
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#ontop)
--- @alias ClientPropertyOnTop boolean
--- @type ClientPropertyOnTop
client.ontop = false

--- The client is above normal windows.
---## Constraints
--- - Default value: `false`
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#above)
--- @alias ClientPropertyAbove boolean
--- @type ClientPropertyAbove
client.above = false

--- The client is below normal windows.
---## Constraints
--- - Default value: `false`
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#below)
--- @alias ClientPropertyBelow boolean
--- @type ClientPropertyBelow
client.below = false

--- The client is fullscreen or not.
---## Constraints
--- - Default value: `false`
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#fullscreen)
--- @alias ClientPropertyFullscreen boolean
--- @type ClientPropertyFullscreen
client.fullscreen = false

--- The client is maximized (horizontally and vertically) or not.
---## Constraints
--- - Default value: `false`
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#maximized)
--- @alias ClientPropertyMaximized boolean
--- @type ClientPropertyMaximized
client.maximized = false

--- The client is maximized horizontally or not.
---## Constraints
--- - Default value: `false`
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#maximized_horizontal)
--- @alias ClientPropertyMaximizedHorizontal boolean
--- @type ClientPropertyMaximizedHorizontal
client.maximized_horizontal = false

--- The client is maximized vertically or not.
---## Constraints
--- - Default value: `false`
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#maximized_vertical)
--- @alias ClientPropertyMaximizedVertical boolean
--- @type ClientPropertyMaximizedVertical
client.maximized_vertical = false

--- The client the window is transient for.
---## Constraints
--- - Access: read-only
--- - Default value: `nil`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#transient_for)
--- @alias ClientPropertyTransientFor Client|nil
--- @type ClientPropertyTransientFor
client.transient_for = nil

--- Window identification unique to a group of windows.
---## Constraints
--- - Access: read-only
--- - Default value: auto-generated by X11
--- - Negative allowed: false
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#group_window)
--- @alias ClientPropertyGroupWindow integer
--- @type ClientPropertyGroupWindow
client.group_window = nil

--- Identification unique to windows spawned by the same command.
---## Constraints
--- - Access: read-only
--- - Default value: auto-generated by X11
--- - Negative allowed: false
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#leader_window)
--- @alias ClientPropertyLeaderWindow integer
--- @type ClientPropertyLeaderWindow
client.leader_window = nil

--- A table with size hints of the client.
---## Constraints
--- - Access: read-only
--- - Default value: nil
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#size_hints)
--- @alias ClientPropertySizeHints ClientSizeHints|nil
--- @type ClientPropertySizeHints
client.size_hints = nil

--- The motif WM hints of the client.
---## Constraints
--- - Access: read-only
--- - Default value: {}
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#motif_wm_hints)
--- @alias ClientPropertyMotifWMHints ClientMotifWMHints
--- @type ClientPropertyMotifWMHints
client.motif_wm_hints = {}

--- Set the client sticky (available on all tags).
---## Constraints
--- - Access: read-only
--- - Default value: `false`
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#sticky)
--- @alias ClientPropertySticky boolean
--- @type ClientPropertySticky
client.sticky = false

--- Indicate if the client is modal.
---## Constraints
--- - Access: read-only
--- - Default value: provided by the application
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#modal)
--- @alias ClientPropertyModal boolean
--- @type ClientPropertyModal
client.modal = nil

--- True if the client can receive the input focus.
---## Constraints
--- - Access: read-only
--- - Default value: `true`
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#focusable)
--- @alias ClientPropertyFocusable boolean
--- @type ClientPropertyFocusable
client.focusable = true

--- The client's bounding shape as set by awesome as a (native) cairo surface.
---## Constraints
--- - Access: read-only
--- - Default value: An A1 surface where all pixels are white.
-- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#shape_bounding)
--- @alias ClientPropertyShapeBounding DrawableImage
--- @type ClientPropertyShapeBounding
client.shape_bounding = nil

--- The client's clip shape as set by awesome as a (native) cairo surface.
---## Constraints
--- - Access: read-only
--- - Default value: An A1 surface where all pixels are white.
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#shape_clip)
--- @alias ClientPropertyShapeClip DrawableImage
--- @type ClientPropertyShapeClip
client.shape_clip = nil

--- The client's input shape as set by awesome as a (native) cairo surface.
---## Constraints
--- - Access: read-only
--- - Default value: An A1 surface where all pixels are white.
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#shape_input)
--- @alias ClientPropertyShapeInput DrawableImage
--- @type ClientPropertyShapeInput
client.shape_input = nil

--- The client's bounding shape as set by the program as a (native) cairo surface.
---## Constraints
--- - Access: read-only
--- - Default value: An A1 surface where all pixels are white
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#client_shape_bounding)
--- @alias ClientPropertyClientShapeBounding DrawableImage
--- @type ClientPropertyClientShapeBounding
client.client_shape_bounding = nil

--- The client's clip shape as set by the program as a (native) cairo surface.
---## Constraints
--- - Access: read-only
--- - Default value: An A1 surface where all pixels are white
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#client_shape_clip)
--- @alias ClientPropertyClientShapeClip DrawableImage
--- @type ClientPropertyClientShapeClip
client.client_shape_clip = nil

--- The FreeDesktop StartId.
---## Constraints
--- - Default value: This is optionally provided by the application
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#startup_id)
--- @alias ClientPropertyStartupId string
--- @type ClientPropertyStartupId
client.startup_id = nil

--- If the client that this object refers to is still managed by awesome.
---## Constraints
--- - Access: read-only
--- - Default value: `true`
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#valid)
--- @alias ClientPropertyValid boolean
--- @type ClientPropertyValid
client.valid = true

--- The first tag of the client.
---
---## Constraints
--- - Access: read-only
--- - Default value: `nil`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#first_tag)
--- @alias ClientPropertyFirstTag Tag | nil
--- @type ClientPropertyFirstTag
client.first_tag = nil

--- Get or set mouse buttons bindings for a client.
---## Constraints
--- - Default value: `{}`
--- - Table content: A list of `awful.buttons` objects
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#buttons)
--- @alias ClientPropertyButtons AwfulButton[]
--- @type ClientPropertyButtons
client.buttons = {}

--- Get or set keys bindings for a client.
---## Constraints
--- - Default value: {}
--- - Table content: A list of `awful.keys` objects
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#keys)
--- @alias ClientPropertyKeys AwfulKey[]
--- @type ClientPropertyKeys
client.keys = {}

--- If a client is marked or not.
---## Constraints
--- - Default value: `false`
--- - Valid values: `true` or `false`
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#marked)
--- @alias ClientPropertyMarked boolean
--- @type ClientPropertyMarked
client.marked = false

--- Return if a client has a fixed size or not.
---## Constraints
--- - Access: read-only
--- - Default value: `false`
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#is_fixed)
--- @alias ClientPropertyIsFixed boolean
--- @type ClientPropertyIsFixed
client.is_fixed = false

--- Is the client immobilized horizontally?
---## Constraints
--- - Access: read-only
--- - Default value: `false`
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#immobilized_horizontal)
--- @alias ClientPropertyImmobilizedHorizontal boolean
--- @type ClientPropertyImmobilizedHorizontal
client.immobilized_horizontal = false

--- Is the client immobilized vertically?
---## Constraints
--- - Access: read-only
--- - Default value: `false`
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#immobilized_vertical)
--- @alias ClientPropertyImmobilizedVertical boolean
--- @type ClientPropertyImmobilizedVertical
client.immobilized_vertical = false

--- The client floating state.
---## Constraints
--- - Default value: `false`
--- - Valid values: `true` or `false`
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#floating)
--- @alias ClientPropertyFloating boolean
--- @type ClientPropertyFloating
client.floating = false

--- The x coordinates.
---
---## Constraints
--- - Default value: `c:geometry().x`
--- - Negative allowed: true
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#x)
--- @alias ClientPropertyX integer
--- @type ClientPropertyX
client.x = client:geometry().x

--- The y coordinates.
---
---## Constraints
--- - Default value: `c:geometry().y`
--- - Negative allowed: true
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#y)
--- @alias ClientPropertyY integer
--- @type ClientPropertyY
client.y = client:geometry().y

--- The width of the client.
---
---## Constraints
--- - Default value: `c:geometry().width`
--- - Minimum value: 1
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#width)
--- @alias ClientPropertyWidth integer
--- @type integer
client.width = client:geometry().width

--- The height of the client.
---
---## Constraints
--- - Default value: `c:geometry().height`
--- - Minimum value: 1
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#height)
--- @alias ClientPropertyHeight integer
--- @type ClientPropertyHeight
client.height = client:geometry().height

--- If the client is dockable.
---## Constraints
--- - Default value: `false`
--- - Valid values: `true` or `false`
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#dockable)
--- @alias ClientPropertyDockable boolean
--- @type ClientPropertyDockable
client.dockable = false

--- If the client requests not to be decorated with a titlebar.
---## Constraints
--- - Default value: `false`
--- - Valid values: Whether the client requests not to get a titlebar
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#requests_no_titlebar)
--- @alias ClientPropertyRequestsNoTitlebar boolean
--- @type ClientPropertyRequestsNoTitlebar
client.requests_no_titlebar = false

--- @alias gears.shape function(cr:cairo.Context, width:integer, height: integer)

--- Set the client shape.
---## Constraints
--- - Default value: `gears.shape.rectangle`
--- - Valid values: A gears.shape compatible function
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#shape)
--- @alias ClientPropertyShape GearsShapeRectangleFn
--- @type ClientPropertyShape
client.shape = gears.shape.rectangle

--- Return true if the client is active (has focus).
---## Constraints
--- - Access: read-only
--- - Default value: `true`
--- - Valid values: `true` or `false`
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/client.html#active)
--- @alias ClientPropertyActive boolean
--- @type ClientPropertyActive
client.active = false
