--- The CAPIStrut structure represents a strut.
--- @class CAPIStrut
--- @field left integer? The left strut value.
--- @field right integer? The right strut value.
--- @field top integer? The top strut value.
--- @field bottom integer? The bottom strut value.
--- @field left_start_y integer? The start y-coordinate of the left strut.
--- @field left_end_y integer? The end y-coordinate of the left strut.
--- @field right_start_y integer? The start y-coordinate of the right strut.
--- @field right_end_y integer? The end y-coordinate of the right strut.
--- @field top_start_x integer? The start x-coordinate of the top strut.
--- @field top_end_x integer? The end x-coordinate of the top strut.
--- @field bottom_start_x integer? The start x-coordinate of the bottom strut.
--- @field bottom_end_x integer? The end x-coordinate of the bottom strut.
