--- ### Description
--- Drawable object.
--- @type DrawableImage
--- ### Constraints
--- - Default value: Autogenerated.
--- ---
--- [**View doc**](https://awesomewm.org/apidoc/core_components/drawable.html#image)
drawable.image = nil
